export const utilitiesData = [
  "Giường ngủ",
  "Giờ giấc tự do",
  "Camera",
  "Thang máy",
  "Ban công",
  "Tủ bếp",
  "Wifi",
  "Thiết bị vệ sinh",
  "Bình nóng lạnh",
  "Điều hòa",
  "Khu để xe",
  "Bàn bếp",
  "Máy giặt",
  "Tủ đồ",
  "Bàn ghế",
  "Không chung chủ",
];
